<h2> DATA 319: Model-based and Data-based Methods for Data Analytics. Summer 2024 </h2>
<h3> Quiz 1. </h3>
<h3> <i> John Salmon. </i></h3>

#### 1. Write a Python code to perform the following tasks:

##### (a) Create a 2x2 `matrix_q1` with following entries: $\begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix}$


In [2]:
matrix_q1 = [[1, 2], [3, 5]]

##### (b) Find and report the determinant of the `matrix_q1`

In [3]:
#ad-bc
q1_det = matrix_q1[0][0] * matrix_q1[1][1] - matrix_q1[0][1] * matrix_q1[1][0]
print(q1_det)


-1


##### (c) Find and report the row sums of the matrix of the `matrix_q1`

In [4]:
print(matrix_q1[0][0] + matrix_q1[0][1])
print(matrix_q1[1][0] + matrix_q1[1][1])

3
8


##### (d) Find and report the column sums of the matrix of the `matrix_q1`

In [10]:
print(matrix_q1[0][0] + matrix_q1[1][0])
print(matrix_q1[0][1] + matrix_q1[1][1])

4
7


##### (e) Create a `vector_q1` $\begin{bmatrix} -1 \\ 5 \end{bmatrix}$ 

In [12]:
vector_q1 = [-1, 5]

##### (f) Find and report the matrix-vector product the `matrix_1` and the `vector_q1` 

In [14]:
product = [matrix_q1[0][0] * vector_q1[0] + matrix_q1[0][1] * vector_q1[1], matrix_q1[1][0] * vector_q1[0] + matrix_q1[1][1] * vector_q1[1]]
print(product)

[9, 22]


#### 2. Write a Python code to perform the following tasks:

##### (a) Create a `vector_q2` consisting of 9 entries, the integers from 1 to 9 $ (1, 2, 3, 4, 5, 6, 7, 8, 9)$ using these three commands
- `np.array()`
- `np.arange()`
- `np.linspace()`



In [19]:
import numpy as np
vector_q2 = np.array(np.arange(1, 10))
print(vector_q2)

[1 2 3 4 5 6 7 8 9]


##### (b) Create a 3x3 `matrix_q2` using `np.reshape()` command from the `vector_q2` you created before 

In [17]:
matrix_q2 = vector_q2.reshape(3,3)
print(matrix_q2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### (c) Find and report the eigenvalues of the `matrix_q2`

In [23]:
print(np.linalg.eig(matrix_q2)[0])

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


##### (d) Find and report the eigenvectors of the `matrix_q2`

In [24]:
print(np.linalg.eig(matrix_q2)[1])

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
